### PR TITLE
Add invisible captcha to login page

### PR DESCRIPTION
**Pull request by RMonteR**
Issues:
1) captcha field is visible
2) login is successful even when captcha field is filled

I had a look at following issues to try and solve the problem:
[https://github.com/markets/invisible_captcha/issues/34](url)
[https://github.com/markets/invisible_captcha/issues/37](url)

@waywho I am sure I am missing sth very simple, and it would be great to check this with you, in order to learn more about the app itself.

### CODE REVIEW

**Comment by waywho** [comment]
You want to generate a new sessions controller and put the gem methods there: https://github.com/plataformatec/devise#configuring-controllers

**Comment by RMonteR** [comment]
- Validation works as intended
- Captcha field is still visible

**Comment by RMonteR** [comment]
I believe the issue is the CSS `display: block` rule from Foundation stylesheet of form elements. Setting `display: none` for the  invisible_captcha`:subtitle` field would solve the issue, but personally I wouldn't do so, since such an info would be easily read by bots. What do you think, @waywho?

**Comment by waywho** [comment]
You can set an id for that input field and then add into the css display: none in the stylesheets (instead of putting it in the attribute of the input).

**Comment by RMonteR** [comment]
Hi @waywho, I have now made the changes and everything works fine. I had to override the commit because some unwanted changes were in the pushed version, as you can see from the back-and-forth last commits.

**Pull request merged**
